### ISSUE TITLE
add team to readme

### ISSUE THREAD

**Issue by lazn** [Stredni-prumyslova-skola-Jesenik/2021_1_01_Multigame#1]
Update readme.md in new development branch
Add team members and their user names

**Comment by jafaktnevimanicmenenapada** [comment]
Done

**Comment by lazn** [comment]
Team member names still missing.

**Comment by jafaktnevimanicmenenapada** [comment]
Member names added

**Comment by lazn** [comment]
Please, add link to the corresponding commit/pull req.
